# On every push this script is executed
on: push

name: Build and deploy GH Pages

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' # ブランチを必要に応じて変更

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy with Zola
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # ターゲットブランチを指定します（通常は'gh-pages'）
          PAGES_BRANCH: gh-pages
          # GitHub Personal Access Tokenを使用してアクセス権を提供します
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # もしくは、同じリポジトリへの公開の場合、自動生成されるGitHubトークンを使用します
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}
